[package]
name = "rdpctl-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rdpctl-core = { path = "../core" }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
glib = { path = "../patches/glib" }
